## Lab: Externalizing Application Configuration

### Background: Application Configuration with ConfigMaps

Most applications require configuration using environment variables,
configuration files and command line arguments. These configuration artifacts
should be externalized form the application and the docker image content in
order to keep the image portable across environments.

ほとんどのアプリケーションでは、環境変数、構成ファイルとコマンドライン引数を使用して構成が必要。これらの構成アーティファクトは、環境間でのイメージの移植性を維持するために、アプリケーションと docker イメージコンテンツを外部形式にする必要があります。

In link:databases[previous labs], the `nationalparks` application was configured with database credentials using environment variables. 
While environment variables is a useful way to configure applications, it is difficult to manage hundreds of environment variables which are scattered across various containers in a project. 
Fortunately, there is a convenient and platform-independent mechanism in OpenShift to configure applications, which is called `ConfigMap`.

以前のlink:databases[演習]では、`nationalparks` アプリケーションは環境変数を使用してデータベース資格情報で構成されていました。
環境変数はアプリケーションを構成するのに便利な方法ですが、プロジェクト内のさまざまなコンテナに散在する数百の環境変数を管理することは困難です。
さいわい、OpenShift には、「ConfigMap」と呼ばれるアプリケーションを構成するための、便利でプラットフォームに依存しないメカニズムがあります。

The `ConfigMap` object in OpenShift provides mechanisms to provide configuration data to the application container while keeping the application images both portable across environments and independent of OpenShift Container Platform. A `ConfigMap` can be used to store key-value properties, configuration files, JSON blobs and alike.

OpenShift の ' ConfigMap ' オブジェクトは、アプリケーションイメージを環境間で移植し、OpenShift コンテナプラットフォームとは無関係に、アプリケーションコンテナに構成データを提供するメカニズムを提供します。' ConfigMap ' は、キーと値のプロパティ、構成ファイル、JSON blob などを格納するために使用できます。

In this lab, you will replace the environment variables provided in the
link:databases[previous labs] and use a `ConfigMap` instead to configure the
`nationalparks` application.

#### Exercise: Create a ConfigMap

You can create a `ConfigMap` by pointing at a file containing the application
configuration. Download this properties file to your local machine which
contains the database credentials: 

[source,role=copypaste]
----
http://gitlab-ce-workshop-infra.{{ROUTER_ADDRESS}}/{{GITLAB_USER}}/nationalparks/raw/{{NATIONALPARKS_VERSION}}/ose3/application-dev.properties
----

NOTE: Verify that the contents of the file are correct. If you have downladed the file with Internet Explorer it might contain
incorrect chars or different charset. Try to use "Google Chrome", "Firefox" or "curl".

Create a `ConfigMap` using the following command in the `{{EXPLORE_PROJECT_NAME}}{{USER_SUFFIX}}` project:
[source]
----
$ oc create configmap nationalparks --from-file=application.properties=./application-dev.properties
----

The `--from-file` option specifies a key-value pair with the key used as the
file name that is provided to the application and value as the content of the
file. In the above command, the content of `application-dev.properties` file
will be provided to the application container as a properties file called
`application.properties`

List and verify that the `ConfigMap` is created successfully containing the
database credentials:

[source]
----
$ oc describe configmap nationalparks

Name:		nationalparks
Namespace:	demo
Labels:		<none>
Annotations:	<none>

Data
====
application.properties:	123 bytes
----


You can review the content of the `ConfigMap` using the `oc get` command:

[source]
----
$ oc get configmap nationalparks -o yaml

apiVersion: v1
data:
  application.properties: |
    # NationalParks MongoDB
    mongodb.server.host=mongodb
    mongodb.user=mongodb
    mongodb.password=mongodb
    mongodb.database=mongodb
kind: ConfigMap
metadata:
  creationTimestamp: 2016-11-16T09:17:02Z
  name: nationalparks
  namespace: {{EXPLORE_PROJECT_NAME}}{{USER_SUFFIX}}
  resourceVersion: "8421"
  selfLink: /api/v1/namespaces/demo/configmaps/nationalparks
  uid: 6f4536cf-abdd-11e6-9282-525400c3c0db
----

#### Exercise: Wire the ConfigMap inside nationalparks Container

Configuration data can be consumed in pods in a variety of ways. A `ConfigMap`
can be used to:

* Populate the value of environment variables
* Set command-line arguments in a container
* Populate configuration files in a volume

The `nationalparks` Spring Boot application can be configured through a
properties file called `application.properties` which should reside in a specific
location in the container filesystem. Using the following command to mount the
`ConfigMap` inside the `nationalparks` pod:

[source]
----
$ oc set volumes dc/nationalparks --add -m /deployments/config --configmap-name=nationalparks
----

The above command makes the content of the configmap `ConfigMap`, which you
created from a file, called `application.properties`, available in the
`/opt/openshift/config` directory. The `nationalparks` *DeploymentConfiguration*
detects the configuration change, and automatically deploys the *Pod* with
the new configuration.

Also, as we have configured `nationalparks` through `ConfigMap`, you can remove
the database environment variables set in the link:databases[previous labs]:

[source]
----
$ oc env dc/nationalparks MONGODB_USER- MONGODB_PASSWORD- MONGODB_DATABASE- MONGODB_SERVER_HOST-
----

You have now externalized `nationalparks` configuration. Visit the `nationalparks` web
service to very the database connection is working correctly.:

[source]
----
http://nationalparks-{{EXPLORE_PROJECT_NAME}}{{USER_SUFFIX}}.{{ROUTER_ADDRESS}}/ws/data/all/
----

If you check the new *Pod's* logs once it comes up, you should see no errors.
