## Lab: Externalizing Application Configuration

### Background: Application Configuration with ConfigMaps

[silver]#Most applications require configuration using environment variables, configuration files and command line arguments. These configuration artifacts should be externalized form the application and the docker image content in order to keep the image portable across environments.#

ほとんどのアプリケーションでは、環境変数、構成ファイルとコマンドライン引数を使用して構成が必要。これらの構成アーティファクトは、環境間でのイメージの移植性を維持するために、アプリケーションと docker イメージコンテンツを外部形式にする必要があります。

[silver]#In link:databases[previous labs], the `nationalparks` application was configured with database credentials using environment variables.  While environment variables is a useful way to configure applications, it is difficult to manage hundreds of environment variables which are scattered across various containers in a project.  Fortunately, there is a convenient and platform-independent mechanism in OpenShift to configure applications, which is called `ConfigMap`.#

以前の link:databases[演習] では、`nationalparks` アプリケーションは環境変数を使用してデータベース資格情報で構成されていました。
環境変数はアプリケーションを構成するのに便利な方法ですが、プロジェクト内のさまざまなコンテナに散在する数百の環境変数を管理することは困難です。
さいわい、OpenShift には、「ConfigMap」と呼ばれるアプリケーションを構成するための、便利でプラットフォームに依存しないメカニズムがあります。

[silver]#The `ConfigMap` object in OpenShift provides mechanisms to provide configuration data to the application container while keeping the application images both portable across environments and independent of OpenShift Container Platform. A `ConfigMap` can be used to store key-value properties, configuration files, JSON blobs and alike.#

OpenShift の `ConfigMap` オブジェクトは、アプリケーションイメージを環境間で移植し、OpenShift コンテナプラットフォームとは無関係に、アプリケーションコンテナに構成データを提供するメカニズムを提供します。`ConfigMap` は、キーと値のプロパティ、構成ファイル、JSON blob などを格納するために使用できます。

[silver]#In this lab, you will replace the environment variables provided in the link:databases[previous labs] and use a `ConfigMap` instead to configure the `nationalparks` application.#

この実習では、link:databases[前の演習]で提供されている環境変数を置き換え、`nationalparks` アプリケーションを構成する代わりに ' ConfigMap ' を使用します。

#### Exercise: Create a ConfigMap

[silver]#You can create a `ConfigMap` by pointing at a file containing the application configuration. Download this properties file to your local machine which contains the database credentials:#

アプリケーション構成を含むファイルをポイントして、ConfigMap を作成できます。データベースの資格情報を含むローカルコンピューターにこのプロパティファイルをダウンロードします。

[source,role=copypaste]
----
http://gogs-workshop-infra.{{ROUTER_ADDRESS}}/{{GITLAB_USER}}/nationalparks/raw/{{NATIONALPARKS_VERSION}}/ose3/application-dev.properties
----

[NOTE]
====
[silver]#Verify that the contents of the file are correct. If you have downladed the file with Internet Explorer it might contain incorrect chars or different charset. Try to use "Google Chrome", "Firefox" or "curl".#

ファイルの内容が正しいことを確認します。Internet Explorer でファイルを downladed している場合は、間違った文字や別の文字セットが含まれている可能性があります。"Google Chrome"、"Firefox" または "curl" を使用してみてください。
====



[silver]#Create a `ConfigMap` using the following command in the `{{EXPLORE_PROJECT_NAME}}{{USER_SUFFIX}}` project:#

`{{EXPLORE_PROJECT_NAME}}{{USER_SUFFIX}}` プロジェクトで次のコマンドを使用して、`ConfigMap` を作成します:

[source]
----
$ oc create configmap nationalparks --from-file=application.properties=./application-dev.properties
----

[silver]#The `--from-file` option specifies a key-value pair with the key used as the file name that is provided to the application and value as the content of the file. In the above command, the content of `application-dev.properties` file will be provided to the application container as a properties file called `application.properties`#

`--from-file` オプションは、アプリケーションに提供されるファイル名として使用されるキーと、ファイルの内容としての値のキーと値のペアを指定します。
上記のコマンドでは、 `application-dev.properties` ファイルの内容は、アプリケーションコンテナに `application.properties` プロパティファイルとして提供されます。

[silver]#List and verify that the `ConfigMap` is created successfully containing the database credentials:#

データベースの資格情報を含む `ConfigMap` が正常に作成されたことを確認します:

[source]
----
$ oc describe configmap nationalparks

Name:		nationalparks
Namespace:	demo
Labels:		<none>
Annotations:	<none>

Data
====
application.properties:	123 bytes
----


[silver]#You can review the content of the `ConfigMap` using the `oc get` command:#

あなたは `oc get` コマンドを使用して `ConfigMap` の内容を確認することができます:

[source]
----
$ oc get configmap nationalparks -o yaml

apiVersion: v1
data:
  application.properties: |
    # NationalParks MongoDB
    mongodb.server.host=mongodb
    mongodb.user=mongodb
    mongodb.password=mongodb
    mongodb.database=mongodb
kind: ConfigMap
metadata:
  creationTimestamp: 2016-11-16T09:17:02Z
  name: nationalparks
  namespace: {{EXPLORE_PROJECT_NAME}}{{USER_SUFFIX}}
  resourceVersion: "8421"
  selfLink: /api/v1/namespaces/demo/configmaps/nationalparks
  uid: 6f4536cf-abdd-11e6-9282-525400c3c0db
----

#### Exercise: Wire the ConfigMap inside nationalparks Container

[silver]#Configuration data can be consumed in pods in a variety of ways. A `ConfigMap` can be used to:#

* [silver]#Populate the value of environment variables#
* [silver]#Set command-line arguments in a container#
* [silver]#Populate configuration files in a volume#

構成データは、さまざまな方法で pod で使用できます。`ConfigMap` は次のように使用できます。

* 環境変数の値を設定する
* コンテナ内のコマンドライン引数を設定する
* ボリューム内の設定ファイルを設定する

[silver]#The `nationalparks` Spring Boot application can be configured through a properties file called `application.properties` which should reside in a specific location in the container filesystem. Using the following command to mount the `ConfigMap` inside the `nationalparks` pod:#

`nationalparks` Spring Boot アプリケーションは、コンテナファイルシステム内の特定の場所に存在する必要があります `application.properties` という名前のプロパティを使用して設定できます。次のコマンドを使用して、`nationalparks` ポッド内の `ConfigMap` をマウントします。

[source]
----
$ oc set volumes dc/nationalparks --add -m /deployments/config --configmap-name=nationalparks
----

[silver]#The above command makes the content of the configmap `ConfigMap`, which you created from a file, called `application.properties`, available in the `/opt/openshift/config` directory. The `nationalparks` *DeploymentConfiguration* detects the configuration change, and automatically deploys the *Pod* with the new configuration.#

上記のコマンドは、`/opt/openshift/config` ディレクトリで利用できる `application.properties` , と呼ばれるファイルから作成したコンフィグレーション定義 `ConfigMap` の内容を作ります。 `nationalparks` の *DeploymentConfiguration* は設定変更を検出し、自動的に *Pod* を新しい設定にデプロイします。

[silver]#Also, as we have configured `nationalparks` through `ConfigMap`, you can remove the database environment variables set in the link:databases[previous labs]:#

また、`ConfigMap` を通じて `nationalparks` を設定しているので、link:databases[前のラボ]で設定されたデータベース環境変数を削除できます。

[source]
----
$ oc env dc/nationalparks MONGODB_USER- MONGODB_PASSWORD- MONGODB_DATABASE- MONGODB_SERVER_HOST-
----

[silver]#You have now externalized `nationalparks` configuration. Visit the `nationalparks` web service to very the database connection is working correctly.:#

あなたは今、外部のプロパティファイルで定義された `nationalparks` の構成を持っている。データベース接続が正常に動作している場合は、`nationalparks` web サービスを参照してください。:

[source]
----
http://nationalparks-{{EXPLORE_PROJECT_NAME}}{{USER_SUFFIX}}.{{ROUTER_ADDRESS}}/ws/data/all/
----

[silver]#If you check the new *Pod's* logs once it comes up, you should see no errors.#

新しい *Pod's* のログを確認する場合は、エラーがないことが確認できます。
