## Lab: Git リポジトリの準備

### 背景

ハンズオンで利用する*nationalparks*アプリケーションのソースコードを確認する。

### Ggosのリポジトリの確認
ラボで利用するためのユーザでリポジトリにログインします。

1. gogsのURLにアクセス
+
{{GITLAB_URL_OPENTLC}}

2. Sign In
+
画面右上の「Sign In」ボタンをクリックしてログイン
+
|===
|Username or email|devXX
|Password|devXX
|===


### リポジトリ作成

1. nationalparks のリポジトリをインポート
+
GogsのDashboard画面の「My Repositories」横にある「+」をクリック
+
「New Migration」をボタンをクリック
+
|===
|Clone Address|http://gogs-komizows.6923.rh-us-east-1.openshiftapps.com/komizo/nationalparks.git
|Owner|dev
|Repository Name|nationalparks
|Visibility|チェックしない
|Migration Type|チェックしない
|===
+
上記を入力後、「Migrate Repository」ボタンをクリック

[NOTE]
====
Webhook がエラーになる場合は、Payloadの内容をファイルに保存し、以下のコマンドを実行
curl -H "X-GitHub-Event: push" -H "Content-Type: application/json" -k -X POST --data-binary @github_payload_file.json https://<openshift_api_host:port>/oapi/v1/namespaces/<namespace>/buildconfigs/<name>/webhooks/<secret>/github
====


### Dev 環境のソールコードリポジトリのURL変更
. 画面右のメニューから *Builds* &rarr; *Builds* を選択
. Builds一覧から nationalparks-dev を選択
. 画面右上の *Actions* メニューから *Edit* を選択
. Git Repository URL を編集
