## Lab: Git リポジトリの準備

### 背景

OpenShift Roadshow では、ハンズオン環境に Git リポジトリなどが用意されている。
Azure Test Drive などを利用する場合でも、OpenShift Roadshow と同様にハンズオン環境にGitリポジトリをデプロイし、*nationalparks*アプリ
ケーションのソースコードを登録しておく。

### GOGSリポジトリのデプロイ
`https://github.com/OpenShiftDemos/gogs-openshift-docker` に登録されている、Postgresql(Ephemeral)を利用するテンプレートを使ってgogsをデプロイする。

#### テンプレートファイルのダウンロード
事前にテンプレートファイルをダウンロードして、作業用ディレクトリに`openshift-gogs-template.yaml`というファイル名で保存します。
```
wget http://bit.ly/openshift-gogs-template -O openshift-gogs-template.yaml
```
### テンプレートを使ってデプロイ

1. OpenShiftのWebコンソールへログイン

2. プロジェクトの作成
+
Welcome to OpenShift画面の中央の「New Project」ボタンをクリックする。

3. プロジェクト名の入力
+
|===
|フィールド|値|説明
|Name(必須)|workshop-infra|プロジェクト名
|Display Name|(空白)|指定した場合は、プロジェクト一覧に表示される
|Description|(空白)|プロジェクトの説明
|===

4. デプロイ方法の選択
+
画面上部のタブで「Import YAML/JSON」を選択

5. YAML ファイルの指定
+
「Browse」ボタンをクリックしてファイル選択ダイアログを表示。ダウンロードしておいたopenshift-gogs-template.yaml を選択。

6. テンプレートを処理
+
画面下部の「Create」ボタンをクリック。
Add Template ダイアログで、「Process the Template」のチェックボックスにチェック。

7. GOGSのデプロイ
+
|===
|フィールド|値
|HOSTNAME|gogs-<プロジェクト名>.<app prefix>
|Skip TLS Verification|true
|===
+
その他のパラメータは変更せず、画面下部の「Create」ボタンをクリック。


[NOTE]
====
Gogsのデプロイに時間がかかるため、何度かヘルスチェックに失敗することがありますが、そのまま待っていてください。
====


### Ggosのユーザー登録
ラボで利用するためのユーザを追加します。

1. workshop-infra プロジェクトを選択

2. gogsのURLをクリック
+
http://{{GITLAB_URL_PREFIX}}.{{ROUTER_ADDRESS}}/

3. Gogs のダッシュボードで「Register」をクリック

4. Sign Up情報を登録
+
フィールドに値を入力し「Create New Account」ボタンをクリック
+
|===
|Username|dev
|Email|dev@example.com
|Password|dev
|Re-Type|dev
|===

5. Sign In
+
先ほど作成したユーザでログイン
+
|===
|Username or email|dev
|Password|dev
|===


### リポジトリ作成

1. nationalparks のリポジトリをインポート
+
GogsのDashboard画面の「My Repositories」横にある「+」をクリック
+
「New Migration」をボタンをクリック
+
|===
|Clone Address|https://github.com/akubicharm/nationalparks
|Owner|dev
|Repository Name|nationalparks
|Visibility|チェックしない
|Migration Type|チェックしない
|===
+
上記を入力後、「Migrate Repository」ボタンをクリック


[NOTE]
====
Webhook がエラーになる場合は、Payloadの内容をファイルに保存し、以下のコマンドを実行
curl -H "X-GitHub-Event: push" -H "Content-Type: application/json" -k -X POST --data-binary @github_payload_file.json https://<openshift_api_host:port>/oapi/v1/namespaces/<namespace>/buildconfigs/<name>/webhooks/<secret>/github
====
