## Lab: Git リポジトリの準備

### 背景

OpenShift Roadshow では、ハンズオン環境に Git リポジトリなどが用意されている。
Azure Test Drive などを利用する場合でも、OpenShift Roadshow と同様にハンズオン環境にGitリポジトリをデプロイし、*nationalparks*アプリ
ケーションのソースコードを登録しておく。

### GOGSリポジトリのデプロイ
`https://github.com/OpenShiftDemos/gogs-openshift-docker` に登録されている、Postgresql(Ephemeral)を利用するテンプレートを使ってgogsをデプロイする。

#### テンプレートファイルのダウンロード
事前にテンプレートファイルをダウンロードして、作業用ディレクトリに`openshift-gogs-template.yaml`というファイル名で保存します。
```
wget http://bit.ly/openshift-gogs-template -O openshift-gogs-template.yaml
```
### テンプレートを使ってデプロイ

1) OpenShiftのWebコンソールへログイン

2) プロジェクトの作成
Welcome to OpenShift画面の中央の「New Project」ボタンをクリックする。

3) プロジェクト名の入力
|===
|フィールド|値|説明
|Name(必須)|workshop-infra|プロジェクト名
|Display Name|(空白)|指定した場合は、プロジェクト一覧に表示される
|Description|(空白)|プロジェクトの説明
|===

4) デプロイ方法の選択
画面上部のタブで「Import YAML/JSON」を選択

5) YAML ファイルの指定
「Browse」ボタンをクリックしてファイル選択ダイアログを表示。ダウンロードしておいたopenshift-gogs-template.yaml を選択。

6) テンプレートを処理
画面下部の「Create」ボタンをクリック。
Add Template ダイアログで、「Process the Template」のチェックボックスにチェック。

7) GOGSのデプロイ
パラメータは変更せず、画面下部の「Create」ボタンをクリック。


[NOTE]
====
Gogsのデプロイに時間がかかるため、何度かヘルスチェックに失敗することがありますが、そのまま待っていてください。
====


### Ggosのユーザー登録
ラボで利用するためのユーザを追加します。

1) workshop-infra プロジェクトを選択

2) gogsのURLをクリック

3) Gogs のダッシュボードで「Register」をクリック

4) Sign Up情報を登録
フィールドに値を入力し「Create New Account」ボタンをクリック
|===
|Username|dev
|Email|dev@example.com
|Password|dev
|Re-Type|dev
|===

5) Sign In
先ほど作成したユーザでログイン
|===
|Username or email|dev
|Password|dev
|===


### リポジトリ作成

1) リポジトリの作成
GogsのDashboard画面の「My Repositories」横にある「+」をクリック
New Repository画面でフィールドに値を入力し、「Create Repository」ボタンをクリック
|===
|Owner|dev
|Repository Name|nationalparks
|===


### nationalparks のソースコードの登録

1) nationalparksソースコード登録ようのJob定義をダウンロード
```
wget https://raw.githubusercontent.com/akubicharm/workshop-setup/master/gitsetup/openshift/gitsetupjob.yaml
```

2) OpenShiftのWebコンソールにログイン

3) workshop-infra プロジェクトを選択

4) 「Add to Project」ボタンをクリック

5) デプロイ方法の選択
画面上部のタブで「Import YAML/JSON」を選択

6) YAML ファイルの指定
「Browse」ボタンをクリックしてファイル選択ダイアログを表示。
gitsetupjob.yaml を選択

7) デプロイ
画面下部の「Create」ボタンをクリック



作業が完了したら、Gogsのnationalparksリポジトリにソースコードが登録されていることを確認しましょう。
