## Lab: Installing the OpenShift CLI

### Command Line Interface

[silver]#OpenShift ships with a feature rich web console as well as command line tools to provide users with a nice interface to work with applications deployed to the platform.  The OpenShift tools are a single executable written in the Go programming language and is available for the following operating systems:#

openshift は、機能豊富な web コンソールだけでなく、コマンドラインツールを使用して、プラットフォームにデプロイされたアプリケーションを操作するための優れたインターフェイスをユーザーに提供します。 openshift ツールは、Go プログラミング言語で記述された単一の実行可能ファイルであり、次のオペレーティングシステムで使用できます。

- Microsoft Windows
- Apple OS X
- Linux

#### Downloading the tools
[silver]#During this lab, we are going to download the client tool and add them to our operating system $PATH environment variables so the executable is accessible from any directory on the command line.#

この演習では、クライアントツールをダウンロードし、オペレーティングシステム $PATH 環境変数に追加して、コマンドライン上の任意のディレクトリから実行可能ファイルにアクセスできるようにします。

[silver]#The first thing we want to do is download the correct executable for your operating system as linked below:#

我々がしたい最初のものは、以下のリンクとして、オペレーティングシステムの正しい実行可能ファイルをダウンロードすることです:

{% if DOWNLOAD_CLIENT_MULTIVERSION %}
**OpenShift 3.4**

 - {{DOWNLOAD_CLIENT_URL}}{{DOWNLOAD_CLIENT_DIR_34}}{{DOWNLOAD_CLIENT_FILE_WINDOWS}}[Microsoft Windows]
 - {{DOWNLOAD_CLIENT_URL}}{{DOWNLOAD_CLIENT_DIR_34}}{{DOWNLOAD_CLIENT_FILE_MAC}}[Apple OS X]
 - {{DOWNLOAD_CLIENT_URL}}{{DOWNLOAD_CLIENT_DIR_34}}{{DOWNLOAD_CLIENT_FILE_LINUX}}[Linux 64]

**OpenShift 3.5**

 - {{DOWNLOAD_CLIENT_URL}}{{DOWNLOAD_CLIENT_DIR_35}}{{DOWNLOAD_CLIENT_FILE_WINDOWS}}[Microsoft Windows]
 - {{DOWNLOAD_CLIENT_URL}}{{DOWNLOAD_CLIENT_DIR_35}}{{DOWNLOAD_CLIENT_FILE_MAC}}[Apple OS X]
 - {{DOWNLOAD_CLIENT_URL}}{{DOWNLOAD_CLIENT_DIR_35}}{{DOWNLOAD_CLIENT_FILE_LINUX}}[Linux 64]

**OpenShift 3.6**

 - {{DOWNLOAD_CLIENT_URL}}{{DOWNLOAD_CLIENT_DIR_36}}{{DOWNLOAD_CLIENT_FILE_WINDOWS}}[Microsoft Windows]
 - {{DOWNLOAD_CLIENT_URL}}{{DOWNLOAD_CLIENT_DIR_36}}{{DOWNLOAD_CLIENT_FILE_MAC}}[Apple OS X]
 - {{DOWNLOAD_CLIENT_URL}}{{DOWNLOAD_CLIENT_DIR_36}}{{DOWNLOAD_CLIENT_FILE_LINUX}}[Linux 64]
{% else %}
- {{DOWNLOAD_CLIENT_WINDOWS}}[Microsoft Windows]
- {{DOWNLOAD_CLIENT_MAC}}[Apple OS X]
- {{DOWNLOAD_CLIENT_LIN64}}[Linux 64]
{% if DOWNLOAD_CLIENT_LIN32.empty? %}
- {{DOWNLOAD_CLIENT_LIN32}}[Linux 32]
{% endif %}
{% endif %}

[silver]#Once the file has been downloaded, you will need to extract the contents as it is a compressed archive.  I would suggest saving this file to the following directories:#

一旦ファイルがダウンロードされたならば、あなたは、それが圧縮されたアーカイブであるので内容を抽出する必要があるでしょう。 私は、次のディレクトリにこのファイルを保存することをお勧め:

**Windows:**

[source]
----
C:\OpenShift
----

**OS X:**

[source]
----
C:\OpenShift

~/OpenShift
----

**Linux:**

[source]
----
~/OpenShift
----

#### Extracting the tools
[silver]#Once you have the tools downloaded, you will need to extract the contents:#

一度ダウンロードしたツールがある場合は、コンテンツを抽出する必要があります:

**Windows:**

[silver]#In order to extract a zip archive on windows, you will need a zip utility installed on your system.  With newer versions of windows (greater than XP), this is provided by the operating system.  Just right click on the downloaded file using file explorer and select to extract the contents.#

windows 上で zip アーカイブを抽出するためには、あなたのシステムにインストールされている zip ユーティリティが必要になります。 windows の新しいバージョン (XP より大きい) では、これはオペレーティングシステムによって提供されます。 ファイルエクスプローラーを使用してダウンロードしたファイルを右クリックして、コンテンツを抽出する を選択します。

**OS X:**

[silver]#Open up a terminal window and change to the directory where you downloaded the file.  Once you are in the directory, enter in the following command:#

ターミナルウィンドウを開き、ファイルをダウンロードしたディレクトリに移動します。 ディレクトリに移動したら、次のコマンドを入力します。

[source,role=copypaste]
----
$ tar zxvf oc-macosx.tar.gz
----
[silver]#The tar.gz file name needs to be replaced by the entire name that was downloaded in the previous step.#

tar.gz ファイル名は、前の手順でダウンロードした名前全体に置き換える必要があります。

**Linux:**

[silver]#Open up a terminal window and change to the directory where you downloaded the file.  Once you are in the directory, enter in the following command:#

ターミナルウィンドウを開き、ファイルをダウンロードしたディレクトリに移動します。 ディレクトリに移動したら、次のコマンドを入力します。

[source,role=copypaste]
----
$ tar zxvf oc-linux.tar.gz
----
[silver]#The tar.gz file name needs to be replaced by the entire name that was downloaded in the previous step.#

tar.gz ファイル名は、前の手順でダウンロードした名前全体に置き換える必要があります。


#### Adding `oc` to your PATH

**Windows:**

[silver]#Because changing your PATH on windows varies by version of the operating system, we will not list each operating system here.  However, the general workflow is right click on your computer name inside of the file explorer.  Select Advanced system settings. I guess changing your PATH is considered an advanced task? :) Click on the advanced tab, and then finally click on Environment variables.  Once the new dialog opens, select the Path variable and add ";C:\OpenShift" at the end.  For an easy way out, you could always just copy it to C:\Windows or a directory you know is already on your path. For more detailed instructions:#

windows でのパスの変更はオペレーティングシステムのバージョンによって異なるため、ここでは各オペレーティングシステムの一覧は表示されません。 ただし、一般的なワークフローは、ファイルエクスプローラー内のコンピューター名を右クリックします。 システムの詳細設定を選択します。私はあなたのパスを変更する高度なタスクと見なされると思いますか? :) 詳細設定タブをクリックし、最後に環境変数をクリックします。 新しいダイアログが開いたら、PATH 変数を選択して追加します。最後に C:\OpenShift。 簡単な方法のために、あなたは、いつもちょうどあなたがあなたのパスにすでに知っている c:\windows またはディレクトリーにそれをコピーすることができました。詳細な手順については:

https://support.microsoft.com/en-us/kb/310519[Windows XP]

http://banagale.com/changing-your-system-path-in-windows-vista.htm[Windows Vista]

http://geekswithblogs.net/renso/archive/2009/10/21/how-to-set-the-windows-path-in-windows-7.aspx[Windows 7]

http://www.itechtics.com/customize-windows-environment-variables/[Windows 8]

Windows 10 - Follow the directions above.

**OS X:**

[source]
----
$ export PATH=$PATH:~/OpenShift
----

**Linux:**

[source]
----
$ export PATH=$PATH:~/OpenShift
----

#### Verify
[silver]#At this point, we should have the oc tool available for use.  Let's test this out by printing the version of the oc command:#

この時点で、oc ツールを使用できるようにする必要があります。 これをテストしましょう。 oc コマンドのバージョンを出力します。

[source]
----
$ oc version
----

[silver]#You should see the following (or something similar):#

次のようなものが表示されます。

[source]
----
{{OC_VERSION}}
----

[silver]#If you get an error message, you have not updated your path correctly.  If you need help, raise your hand and the instructor will assist.#


エラーメッセージが表示された場合は、パスを正しく更新していません。 助けが必要な場合は、手を上げるとインストラクターが支援します。
